name: Rodar script Python diário

on:
  schedule:
    - cron: '10 10 * * *'  # todo dia às 10:10 UTC
  workflow_dispatch:       # permite rodar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Executar script
        run: python acompanhamento_lme2.py
